#!/usr/bin/env perl

use v5.36;
use autodie;

use DBI;
use YAML::Tiny;
use Path::Tiny;
use Text::Xslate;
use Data::Dumper;
use Getopt::Long;

our $config = YAML::Tiny->read($ENV{MOMIJI_CONFIG_FILE} || 'config.yml');

our $tx = Text::Xslate->new(
  cache => $ENV{PLACK_ENV} eq 'development' ? 0 : 1,
  path => ['view'],
  pre_process_handler => sub {
    my $text = shift;
    $text =~ s/\n+\s*/ /g;
    $text
  }
);

our $dbh = DBI->connect("dbi:SQLite:dbname=momiji.sqlite3", "", "");

sub init_boards {

}